version: '3'

services:
#
#  frontend:
#    build:
#      context: .
#      dockerfile: ./frontapp/Dockerfile
#    command: npm run serve
#    ports:
#      - 8080:8080
#    depends_on:
#      - app

  db:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234user
      - POSTGRES_DB=compose-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/

  app:
    build: .
    working_dir: /app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=1234user
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: mvn clean spring-boot:run
    depends_on:
      - db

